// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: record.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncStatus int32

const (
	SyncStatus_SYNC_STATUS_UNSPECIFIED SyncStatus = 0
	SyncStatus_SYNC_STATUS_PENDING     SyncStatus = 1
	SyncStatus_SYNC_STATUS_PROCESSING  SyncStatus = 2
	SyncStatus_SYNC_STATUS_DONE        SyncStatus = 3
	SyncStatus_SYNC_STATUS_FAILED      SyncStatus = 4
)

// Enum value maps for SyncStatus.
var (
	SyncStatus_name = map[int32]string{
		0: "SYNC_STATUS_UNSPECIFIED",
		1: "SYNC_STATUS_PENDING",
		2: "SYNC_STATUS_PROCESSING",
		3: "SYNC_STATUS_DONE",
		4: "SYNC_STATUS_FAILED",
	}
	SyncStatus_value = map[string]int32{
		"SYNC_STATUS_UNSPECIFIED": 0,
		"SYNC_STATUS_PENDING":     1,
		"SYNC_STATUS_PROCESSING":  2,
		"SYNC_STATUS_DONE":        3,
		"SYNC_STATUS_FAILED":      4,
	}
)

func (x SyncStatus) Enum() *SyncStatus {
	p := new(SyncStatus)
	*p = x
	return p
}

func (x SyncStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_record_proto_enumTypes[0].Descriptor()
}

func (SyncStatus) Type() protoreflect.EnumType {
	return &file_record_proto_enumTypes[0]
}

func (x SyncStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncStatus.Descriptor instead.
func (SyncStatus) EnumDescriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0}
}

// パイプラインを流れる Driveファイルの型
type FileRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriveFileId   string                 `protobuf:"bytes,1,opt,name=drive_file_id,json=driveFileId,proto3" json:"drive_file_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SyncStatus    SyncStatus             `protobuf:"varint,5,opt,name=sync_status,json=syncStatus,proto3,enum=record.SyncStatus" json:"sync_status,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRecord) Reset() {
	*x = FileRecord{}
	mi := &file_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRecord) ProtoMessage() {}

func (x *FileRecord) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRecord.ProtoReflect.Descriptor instead.
func (*FileRecord) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{0}
}

func (x *FileRecord) GetDriveFileId() string {
	if x != nil {
		return x.DriveFileId
	}
	return ""
}

func (x *FileRecord) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRecord) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *FileRecord) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileRecord) GetSyncStatus() SyncStatus {
	if x != nil {
		return x.SyncStatus
	}
	return SyncStatus_SYNC_STATUS_UNSPECIFIED
}

func (x *FileRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ファイルを分割したチャンクの型
type ChunkRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FileId          string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	ChunkIndex      int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	EmbeddingStatus string                 `protobuf:"bytes,4,opt,name=embedding_status,json=embeddingStatus,proto3" json:"embedding_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChunkRecord) Reset() {
	*x = ChunkRecord{}
	mi := &file_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRecord) ProtoMessage() {}

func (x *ChunkRecord) ProtoReflect() protoreflect.Message {
	mi := &file_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRecord.ProtoReflect.Descriptor instead.
func (*ChunkRecord) Descriptor() ([]byte, []int) {
	return file_record_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkRecord) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *ChunkRecord) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChunkRecord) GetEmbeddingStatus() string {
	if x != nil {
		return x.EmbeddingStatus
	}
	return ""
}

var File_record_proto protoreflect.FileDescriptor

const file_record_proto_rawDesc = "" +
	"\n" +
	"\frecord.proto\x12\x06record\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x01\n" +
	"\n" +
	"FileRecord\x12\"\n" +
	"\rdrive_file_id\x18\x01 \x01(\tR\vdriveFileId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x123\n" +
	"\vsync_status\x18\x05 \x01(\x0e2\x12.record.SyncStatusR\n" +
	"syncStatus\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8c\x01\n" +
	"\vChunkRecord\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12)\n" +
	"\x10embedding_status\x18\x04 \x01(\tR\x0fembeddingStatus*\x8c\x01\n" +
	"\n" +
	"SyncStatus\x12\x1b\n" +
	"\x17SYNC_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SYNC_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16SYNC_STATUS_PROCESSING\x10\x02\x12\x14\n" +
	"\x10SYNC_STATUS_DONE\x10\x03\x12\x16\n" +
	"\x12SYNC_STATUS_FAILED\x10\x04B2Z0github.com/qei-2027-700/go-drive-etl/internal/pbb\x06proto3"

var (
	file_record_proto_rawDescOnce sync.Once
	file_record_proto_rawDescData []byte
)

func file_record_proto_rawDescGZIP() []byte {
	file_record_proto_rawDescOnce.Do(func() {
		file_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_record_proto_rawDesc), len(file_record_proto_rawDesc)))
	})
	return file_record_proto_rawDescData
}

var file_record_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_record_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_record_proto_goTypes = []any{
	(SyncStatus)(0),               // 0: record.SyncStatus
	(*FileRecord)(nil),            // 1: record.FileRecord
	(*ChunkRecord)(nil),           // 2: record.ChunkRecord
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_record_proto_depIdxs = []int32{
	0, // 0: record.FileRecord.sync_status:type_name -> record.SyncStatus
	3, // 1: record.FileRecord.updated_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_record_proto_init() }
func file_record_proto_init() {
	if File_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_record_proto_rawDesc), len(file_record_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_record_proto_goTypes,
		DependencyIndexes: file_record_proto_depIdxs,
		EnumInfos:         file_record_proto_enumTypes,
		MessageInfos:      file_record_proto_msgTypes,
	}.Build()
	File_record_proto = out.File
	file_record_proto_goTypes = nil
	file_record_proto_depIdxs = nil
}
