// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/file_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/file_repository.go -destination=internal/repository/mock/mock_file_repo.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/qei-2027-700/go-drive-etl/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFileRepo is a mock of FileRepo interface.
type MockFileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepoMockRecorder
	isgomock struct{}
}

// MockFileRepoMockRecorder is the mock recorder for MockFileRepo.
type MockFileRepoMockRecorder struct {
	mock *MockFileRepo
}

// NewMockFileRepo creates a new mock instance.
func NewMockFileRepo(ctrl *gomock.Controller) *MockFileRepo {
	mock := &MockFileRepo{ctrl: ctrl}
	mock.recorder = &MockFileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepo) EXPECT() *MockFileRepoMockRecorder {
	return m.recorder
}

// ListPending mocks base method.
func (m *MockFileRepo) ListPending(ctx context.Context) ([]*domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx)
	ret0, _ := ret[0].([]*domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockFileRepoMockRecorder) ListPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockFileRepo)(nil).ListPending), ctx)
}

// UpdateStatus mocks base method.
func (m *MockFileRepo) UpdateStatus(ctx context.Context, fileID int64, status domain.SyncStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, fileID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockFileRepoMockRecorder) UpdateStatus(ctx, fileID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockFileRepo)(nil).UpdateStatus), ctx, fileID, status)
}

// Upsert mocks base method.
func (m *MockFileRepo) Upsert(ctx context.Context, f *domain.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockFileRepoMockRecorder) Upsert(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockFileRepo)(nil).Upsert), ctx, f)
}
