// Code generated by MockGen. DO NOT EDIT.
// Source: internal/bq/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/bq/client.go -destination=internal/bq/mock/mock_bq_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	bigquery "cloud.google.com/go/bigquery"
	gomock "go.uber.org/mock/gomock"
)

// MockBQClient is a mock of BQClient interface.
type MockBQClient struct {
	ctrl     *gomock.Controller
	recorder *MockBQClientMockRecorder
	isgomock struct{}
}

// MockBQClientMockRecorder is the mock recorder for MockBQClient.
type MockBQClientMockRecorder struct {
	mock *MockBQClient
}

// NewMockBQClient creates a new mock instance.
func NewMockBQClient(ctrl *gomock.Controller) *MockBQClient {
	mock := &MockBQClient{ctrl: ctrl}
	mock.recorder = &MockBQClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBQClient) EXPECT() *MockBQClientMockRecorder {
	return m.recorder
}

// InsertRows mocks base method.
func (m *MockBQClient) InsertRows(ctx context.Context, table string, rows []map[string]bigquery.Value) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRows", ctx, table, rows)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertRows indicates an expected call of InsertRows.
func (mr *MockBQClientMockRecorder) InsertRows(ctx, table, rows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRows", reflect.TypeOf((*MockBQClient)(nil).InsertRows), ctx, table, rows)
}
