// Code generated by MockGen. DO NOT EDIT.
// Source: internal/etl/worker_pool.go
//
// Generated by this command:
//
//	mockgen -source=internal/etl/worker_pool.go -destination=internal/etl/mock/mock_worker_pool.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	bq "github.com/qei-2027-700/go-drive-etl/internal/bq"
	drive "github.com/qei-2027-700/go-drive-etl/internal/drive"
	repository "github.com/qei-2027-700/go-drive-etl/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkerPool is a mock of WorkerPool interface.
type MockWorkerPool struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerPoolMockRecorder
	isgomock struct{}
}

// MockWorkerPoolMockRecorder is the mock recorder for MockWorkerPool.
type MockWorkerPoolMockRecorder struct {
	mock *MockWorkerPool
}

// NewMockWorkerPool creates a new mock instance.
func NewMockWorkerPool(ctrl *gomock.Controller) *MockWorkerPool {
	mock := &MockWorkerPool{ctrl: ctrl}
	mock.recorder = &MockWorkerPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkerPool) EXPECT() *MockWorkerPoolMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockWorkerPool) Run(ctx context.Context, repo repository.FileRepo, driveClient drive.DriveClient, bqClient bq.BQClient) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, repo, driveClient, bqClient)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockWorkerPoolMockRecorder) Run(ctx, repo, driveClient, bqClient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockWorkerPool)(nil).Run), ctx, repo, driveClient, bqClient)
}
