// Code generated by MockGen. DO NOT EDIT.
// Source: internal/drive/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/drive/client.go -destination=internal/drive/mock/mock_drive_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	drive "google.golang.org/api/drive/v3"
)

// MockDriveClient is a mock of DriveClient interface.
type MockDriveClient struct {
	ctrl     *gomock.Controller
	recorder *MockDriveClientMockRecorder
	isgomock struct{}
}

// MockDriveClientMockRecorder is the mock recorder for MockDriveClient.
type MockDriveClientMockRecorder struct {
	mock *MockDriveClient
}

// NewMockDriveClient creates a new mock instance.
func NewMockDriveClient(ctrl *gomock.Controller) *MockDriveClient {
	mock := &MockDriveClient{ctrl: ctrl}
	mock.recorder = &MockDriveClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriveClient) EXPECT() *MockDriveClientMockRecorder {
	return m.recorder
}

// ListFiles mocks base method.
func (m *MockDriveClient) ListFiles(ctx context.Context, folderID string) ([]*drive.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", ctx, folderID)
	ret0, _ := ret[0].([]*drive.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockDriveClientMockRecorder) ListFiles(ctx, folderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockDriveClient)(nil).ListFiles), ctx, folderID)
}
